version: "3"

env:
  OAPI_GENERATOR_IMAGE: docker.io/openapitools/openapi-generator-cli:v6.6.0

tasks:
  generate:
    desc: Run all code generators.
    cmds:
      - task: api:lua:authentication
      - task: api:lua:connect

  api:lua:authentication:
    desc: Run lua code generation for the Authentication API.
    cmds:
      - |
        rm -r ./clients/lua/authentication || true

        podman run \
          --rm \
          --security-opt label=disable \
          -v $(pwd):/local ${OAPI_GENERATOR_IMAGE} generate \
          -i /local/apis/authentication.yaml \
          -c /local/config/lua/authentication.yaml \
          -o /local/clients/lua/authentication \
          -g lua

  api:lua:connect:
    desc: Run lua code generation for the Connect API.
    cmds:
      - |
        rm -r ./clients/lua/connect || true

        podman run \
          --rm \
          --security-opt label=disable \
          -v $(pwd):/local ${OAPI_GENERATOR_IMAGE} generate \
          -i /local/apis/connect.yaml \
          -c /local/config/lua/connect.yaml \
          -o /local/clients/lua/connect \
          -g lua
