package = "connect"
version = "1.0.0-1"
source = {
	url = "https://github.com/GIT_USER_ID/GIT_REPO_ID.git"
}

description = {
	summary = "API client generated by OpenAPI Generator",
	detailed = [[
This API allows you to control and obtain information about Automower®.]],
	homepage = "https://openapi-generator.tech",
	license = "Unlicense",
	maintainer = "OpenAPI Generator contributors",
}

dependencies = {
	"lua >= 5.2",
	"http",
	"dkjson",
	"basexx"
}

build = {
	type = "builtin",
	modules = {
		["connect.api.actions_api"] = "connect/api/actions_api.lua";
		["connect.api.mower_api"] = "connect/api/mower_api.lua";
		["connect.model._mowers__id__actions_post_request"] = "connect/model/_mowers__id__actions_post_request.lua";
		["connect.model._mowers__id__actions_post_request_data"] = "connect/model/_mowers__id__actions_post_request_data.lua";
		["connect.model._mowers__id__calendar_post_request"] = "connect/model/_mowers__id__calendar_post_request.lua";
		["connect.model._mowers__id__calendar_post_request_data"] = "connect/model/_mowers__id__calendar_post_request_data.lua";
		["connect.model._mowers__id__calendar_post_request_data_attributes"] = "connect/model/_mowers__id__calendar_post_request_data_attributes.lua";
		["connect.model._mowers__id__settings_post_request"] = "connect/model/_mowers__id__settings_post_request.lua";
		["connect.model._mowers__id__settings_post_request_data"] = "connect/model/_mowers__id__settings_post_request_data.lua";
		["connect.model._mowers__id__settings_post_request_data_attributes"] = "connect/model/_mowers__id__settings_post_request_data_attributes.lua";
		["connect.model.battery"] = "connect/model/battery.lua";
		["connect.model.calendar"] = "connect/model/calendar.lua";
		["connect.model.calendar_task"] = "connect/model/calendar_task.lua";
		["connect.model.cutting_height"] = "connect/model/cutting_height.lua";
		["connect.model.duration_attributes"] = "connect/model/duration_attributes.lua";
		["connect.model.headlight"] = "connect/model/headlight.lua";
		["connect.model.headlight_headlight"] = "connect/model/headlight_headlight.lua";
		["connect.model.json_api_action"] = "connect/model/json_api_action.lua";
		["connect.model.json_api_data"] = "connect/model/json_api_data.lua";
		["connect.model.json_api_data_command_result"] = "connect/model/json_api_data_command_result.lua";
		["connect.model.json_api_data_document"] = "connect/model/json_api_data_document.lua";
		["connect.model.json_api_data_document_command_result"] = "connect/model/json_api_data_document_command_result.lua";
		["connect.model.json_api_data_document_list_command_result"] = "connect/model/json_api_data_document_list_command_result.lua";
		["connect.model.json_api_data_list_document"] = "connect/model/json_api_data_list_document.lua";
		["connect.model.json_api_error"] = "connect/model/json_api_error.lua";
		["connect.model.json_api_error_document"] = "connect/model/json_api_error_document.lua";
		["connect.model.metadata"] = "connect/model/metadata.lua";
		["connect.model.mower_app"] = "connect/model/mower_app.lua";
		["connect.model.mower_data"] = "connect/model/mower_data.lua";
		["connect.model.park"] = "connect/model/park.lua";
		["connect.model.park_until_further_notice"] = "connect/model/park_until_further_notice.lua";
		["connect.model.park_until_next_schedule"] = "connect/model/park_until_next_schedule.lua";
		["connect.model.pause"] = "connect/model/pause.lua";
		["connect.model.planner"] = "connect/model/planner.lua";
		["connect.model.planner_override"] = "connect/model/planner_override.lua";
		["connect.model.position"] = "connect/model/position.lua";
		["connect.model.resume_schedule"] = "connect/model/resume_schedule.lua";
		["connect.model.settings"] = "connect/model/settings.lua";
		["connect.model.start"] = "connect/model/start.lua";
		["connect.model.start_all_of"] = "connect/model/start_all_of.lua";
		["connect.model.statistics"] = "connect/model/statistics.lua";
		["connect.model.system"] = "connect/model/system.lua";
	}
}
