--[[
  Authentication API

  Husqvarna Group Authentication API

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- post_o_auth2_response class
local post_o_auth2_response = {}
local post_o_auth2_response_mt = {
	__name = "post_o_auth2_response";
	__index = post_o_auth2_response;
}

local function cast_post_o_auth2_response(t)
	return setmetatable(t, post_o_auth2_response_mt)
end

local function new_post_o_auth2_response(access_token, scope, expires_in, refresh_token, provider, user_id, token_type)
	return cast_post_o_auth2_response({
		["access_token"] = access_token;
		["scope"] = scope;
		["expires_in"] = expires_in;
		["refresh_token"] = refresh_token;
		["provider"] = provider;
		["user_id"] = user_id;
		["token_type"] = token_type;
	})
end

return {
	cast = cast_post_o_auth2_response;
	new = new_post_o_auth2_response;
}
