--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- _mowers__id__settings_post_request class
local _mowers__id__settings_post_request = {}
local _mowers__id__settings_post_request_mt = {
	__name = "_mowers__id__settings_post_request";
	__index = _mowers__id__settings_post_request;
}

local function cast__mowers__id__settings_post_request(t)
	return setmetatable(t, _mowers__id__settings_post_request_mt)
end

local function new__mowers__id__settings_post_request(data)
	return cast__mowers__id__settings_post_request({
		["data"] = data;
	})
end

return {
	cast = cast__mowers__id__settings_post_request;
	new = new__mowers__id__settings_post_request;
}
