--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- _mowers__id__actions_post_request_data class
local _mowers__id__actions_post_request_data = {}
local _mowers__id__actions_post_request_data_mt = {
	__name = "_mowers__id__actions_post_request_data";
	__index = _mowers__id__actions_post_request_data;
}

local function cast__mowers__id__actions_post_request_data(t)
	return setmetatable(t, _mowers__id__actions_post_request_data_mt)
end

local function new__mowers__id__actions_post_request_data(type, attributes)
	return cast__mowers__id__actions_post_request_data({
		["type"] = type;
		["attributes"] = attributes;
	})
end

return {
	cast = cast__mowers__id__actions_post_request_data;
	new = new__mowers__id__actions_post_request_data;
}
