--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- battery class
local battery = {}
local battery_mt = {
	__name = "battery";
	__index = battery;
}

local function cast_battery(t)
	return setmetatable(t, battery_mt)
end

local function new_battery(battery_percent)
	return cast_battery({
		["batteryPercent"] = battery_percent;
	})
end

return {
	cast = cast_battery;
	new = new_battery;
}
