--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- calendar_task class
local calendar_task = {}
local calendar_task_mt = {
	__name = "calendar_task";
	__index = calendar_task;
}

local function cast_calendar_task(t)
	return setmetatable(t, calendar_task_mt)
end

local function new_calendar_task(start, duration, monday, tuesday, wednesday, thursday, friday, saturday, sunday)
	return cast_calendar_task({
		["start"] = start;
		["duration"] = duration;
		["monday"] = monday;
		["tuesday"] = tuesday;
		["wednesday"] = wednesday;
		["thursday"] = thursday;
		["friday"] = friday;
		["saturday"] = saturday;
		["sunday"] = sunday;
	})
end

return {
	cast = cast_calendar_task;
	new = new_calendar_task;
}
