--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- calendar class
local calendar = {}
local calendar_mt = {
	__name = "calendar";
	__index = calendar;
}

local function cast_calendar(t)
	return setmetatable(t, calendar_mt)
end

local function new_calendar(tasks)
	return cast_calendar({
		["tasks"] = tasks;
	})
end

return {
	cast = cast_calendar;
	new = new_calendar;
}
