--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- cutting_height class
local cutting_height = {}
local cutting_height_mt = {
	__name = "cutting_height";
	__index = cutting_height;
}

local function cast_cutting_height(t)
	return setmetatable(t, cutting_height_mt)
end

local function new_cutting_height(cutting_height)
	return cast_cutting_height({
		["cuttingHeight"] = cutting_height;
	})
end

return {
	cast = cast_cutting_height;
	new = new_cutting_height;
}
