--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- duration_attributes class
local duration_attributes = {}
local duration_attributes_mt = {
	__name = "duration_attributes";
	__index = duration_attributes;
}

local function cast_duration_attributes(t)
	return setmetatable(t, duration_attributes_mt)
end

local function new_duration_attributes(duration)
	return cast_duration_attributes({
		["duration"] = duration;
	})
end

return {
	cast = cast_duration_attributes;
	new = new_duration_attributes;
}
