--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- headlight class
local headlight = {}
local headlight_mt = {
	__name = "headlight";
	__index = headlight;
}

local function cast_headlight(t)
	return setmetatable(t, headlight_mt)
end

local function new_headlight(headlight)
	return cast_headlight({
		["headlight"] = headlight;
	})
end

return {
	cast = cast_headlight;
	new = new_headlight;
}
