--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- headlight_headlight class
local headlight_headlight = {}
local headlight_headlight_mt = {
	__name = "headlight_headlight";
	__index = headlight_headlight;
}

local function cast_headlight_headlight(t)
	return setmetatable(t, headlight_headlight_mt)
end

local function new_headlight_headlight(mode)
	return cast_headlight_headlight({
		["mode"] = mode;
	})
end

return {
	cast = cast_headlight_headlight;
	new = new_headlight_headlight;
}
