--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- json_api_data class
local json_api_data = {}
local json_api_data_mt = {
	__name = "json_api_data";
	__index = json_api_data;
}

local function cast_json_api_data(t)
	return setmetatable(t, json_api_data_mt)
end

local function new_json_api_data(type, id, attributes)
	return cast_json_api_data({
		["type"] = type;
		["id"] = id;
		["attributes"] = attributes;
	})
end

return {
	cast = cast_json_api_data;
	new = new_json_api_data;
}
