--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- json_api_action class
local json_api_action = {}
local json_api_action_mt = {
	__name = "json_api_action";
	__index = json_api_action;
}

local function cast_json_api_action(t)
	return setmetatable(t, json_api_action_mt)
end

local function new_json_api_action(type)
	return cast_json_api_action({
		["type"] = type;
	})
end

return {
	cast = cast_json_api_action;
	new = new_json_api_action;
}
