--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- metadata class
local metadata = {}
local metadata_mt = {
	__name = "metadata";
	__index = metadata;
}

local function cast_metadata(t)
	return setmetatable(t, metadata_mt)
end

local function new_metadata(connected, status_timestamp)
	return cast_metadata({
		["connected"] = connected;
		["statusTimestamp"] = status_timestamp;
	})
end

return {
	cast = cast_metadata;
	new = new_metadata;
}
