--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- mower_app class
local mower_app = {}
local mower_app_mt = {
	__name = "mower_app";
	__index = mower_app;
}

local function cast_mower_app(t)
	return setmetatable(t, mower_app_mt)
end

local function new_mower_app(mode, activity, state, error_code, error_code_timestamp)
	return cast_mower_app({
		["mode"] = mode;
		["activity"] = activity;
		["state"] = state;
		["errorCode"] = error_code;
		["errorCodeTimestamp"] = error_code_timestamp;
	})
end

return {
	cast = cast_mower_app;
	new = new_mower_app;
}
