--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- mower_data class
local mower_data = {}
local mower_data_mt = {
	__name = "mower_data";
	__index = mower_data;
}

local function cast_mower_data(t)
	return setmetatable(t, mower_data_mt)
end

local function new_mower_data(system, battery, mower, calendar, planner, metadata, positions, settings, statistics)
	return cast_mower_data({
		["system"] = system;
		["battery"] = battery;
		["mower"] = mower;
		["calendar"] = calendar;
		["planner"] = planner;
		["metadata"] = metadata;
		["positions"] = positions;
		["settings"] = settings;
		["statistics"] = statistics;
	})
end

return {
	cast = cast_mower_data;
	new = new_mower_data;
}
