--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- park_until_next_schedule class
local park_until_next_schedule = {}
local park_until_next_schedule_mt = {
	__name = "park_until_next_schedule";
	__index = park_until_next_schedule;
}

local function cast_park_until_next_schedule(t)
	return setmetatable(t, park_until_next_schedule_mt)
end

local function new_park_until_next_schedule(type)
	return cast_park_until_next_schedule({
		["type"] = type;
	})
end

return {
	cast = cast_park_until_next_schedule;
	new = new_park_until_next_schedule;
}
