--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- park_until_further_notice class
local park_until_further_notice = {}
local park_until_further_notice_mt = {
	__name = "park_until_further_notice";
	__index = park_until_further_notice;
}

local function cast_park_until_further_notice(t)
	return setmetatable(t, park_until_further_notice_mt)
end

local function new_park_until_further_notice(type)
	return cast_park_until_further_notice({
		["type"] = type;
	})
end

return {
	cast = cast_park_until_further_notice;
	new = new_park_until_further_notice;
}
