--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- pause class
local pause = {}
local pause_mt = {
	__name = "pause";
	__index = pause;
}

local function cast_pause(t)
	return setmetatable(t, pause_mt)
end

local function new_pause(type)
	return cast_pause({
		["type"] = type;
	})
end

return {
	cast = cast_pause;
	new = new_pause;
}
