--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- planner class
local planner = {}
local planner_mt = {
	__name = "planner";
	__index = planner;
}

local function cast_planner(t)
	return setmetatable(t, planner_mt)
end

local function new_planner(next_start_timestamp, override, restricted_reason)
	return cast_planner({
		["nextStartTimestamp"] = next_start_timestamp;
		["override"] = override;
		["restrictedReason"] = restricted_reason;
	})
end

return {
	cast = cast_planner;
	new = new_planner;
}
