--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- planner_override class
local planner_override = {}
local planner_override_mt = {
	__name = "planner_override";
	__index = planner_override;
}

local function cast_planner_override(t)
	return setmetatable(t, planner_override_mt)
end

local function new_planner_override(action)
	return cast_planner_override({
		["action"] = action;
	})
end

return {
	cast = cast_planner_override;
	new = new_planner_override;
}
