--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- resume_schedule class
local resume_schedule = {}
local resume_schedule_mt = {
	__name = "resume_schedule";
	__index = resume_schedule;
}

local function cast_resume_schedule(t)
	return setmetatable(t, resume_schedule_mt)
end

local function new_resume_schedule(type)
	return cast_resume_schedule({
		["type"] = type;
	})
end

return {
	cast = cast_resume_schedule;
	new = new_resume_schedule;
}
