--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- settings class
local settings = {}
local settings_mt = {
	__name = "settings";
	__index = settings;
}

local function cast_settings(t)
	return setmetatable(t, settings_mt)
end

local function new_settings(cutting_height, headlight)
	return cast_settings({
		["cuttingHeight"] = cutting_height;
		["headlight"] = headlight;
	})
end

return {
	cast = cast_settings;
	new = new_settings;
}
