--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- start class
local start = {}
local start_mt = {
	__name = "start";
	__index = start;
}

local function cast_start(t)
	return setmetatable(t, start_mt)
end

local function new_start(type, attributes)
	return cast_start({
		["type"] = type;
		["attributes"] = attributes;
	})
end

return {
	cast = cast_start;
	new = new_start;
}
