--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- statistics class
local statistics = {}
local statistics_mt = {
	__name = "statistics";
	__index = statistics;
}

local function cast_statistics(t)
	return setmetatable(t, statistics_mt)
end

local function new_statistics(cutting_blade_usage_time, number_of_charging_cycles, number_of_collisions, total_charging_time, total_cutting_time, total_running_time, total_searching_time)
	return cast_statistics({
		["cuttingBladeUsageTime"] = cutting_blade_usage_time;
		["numberOfChargingCycles"] = number_of_charging_cycles;
		["numberOfCollisions"] = number_of_collisions;
		["totalChargingTime"] = total_charging_time;
		["totalCuttingTime"] = total_cutting_time;
		["totalRunningTime"] = total_running_time;
		["totalSearchingTime"] = total_searching_time;
	})
end

return {
	cast = cast_statistics;
	new = new_statistics;
}
