--[[
  Automower® Connect API

  This API allows you to control and obtain information about Automower®.

  The version of the OpenAPI document: 1.0.0
  
  Generated by: https://openapi-generator.tech
]]

-- system class
local system = {}
local system_mt = {
	__name = "system";
	__index = system;
}

local function cast_system(t)
	return setmetatable(t, system_mt)
end

local function new_system(name, model, serial_number)
	return cast_system({
		["name"] = name;
		["model"] = model;
		["serialNumber"] = serial_number;
	})
end

return {
	cast = cast_system;
	new = new_system;
}
